import { StyleSheet } from "react-native";
const styles = StyleSheet.create({
  container: {
    width: "49%",
    minWidth: "49%",
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 8,
    borderColor: "#ddd",
    borderWidth: 1,
    padding: 10,
    marginBottom: 10,
    marginHorizontal: 2,
    backgroundColor: "white",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
    position: "relative",
  },
  image: { width: 120, height: 120, resizeMode: "cover" },
  containerInfo: {
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-start",
    alignItems: "flex-start",
    width: "100%",
  },
  title: {
    fontWeight: "bold",
    fontSize: 16,
    color: "#009C94",
    textAlign: "center",
    textTransform: "capitalize",
    width: "100%",
    marginBottom: 10,
  },
  description: {
    fontSize: 14,
    color: "#555",
    marginBottom: 10,
    width: "100%",
  },
  price: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#009C94",
  },
  rating: {
    position: "absolute",
    top: -5,
    right: -5,
    backgroundColor: "#FFD700",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 4,
    transform: [{ rotate: "30deg" }],
  },
  deleteBtn: {
    position: "absolute",
    top: -5,
    right: -5,
  },
});

export default styles;
